[tox]
envlist = py311,py312,py313
isolated_build = true

[testenv]
deps =
    ruff>=0.6,<0.7
    mypy>=1.13,<2
    types-requests>=2.32,<3
commands =
    ruff check blackbox_ci
    ruff format --check blackbox_ci
    mypy --strict blackbox_ci